"""
report_writer.py

Saves AI-generated incident reports to a text file.
"""

import os
from datetime import datetime

# Output folder
OUTPUT_FOLDER = "output"


def save_report(report):
    """
    Saves the AI-generated report to a TXT file.

    Args:
        report (str): AI-generated incident report.

    Returns:
        str: Path of the saved report.
    """

    # Create output folder if it doesn't exist
    os.makedirs(OUTPUT_FOLDER, exist_ok=True)

    file_path = os.path.join(
        OUTPUT_FOLDER,
        "incident_report.txt"
    )

    with open(file_path, "w", encoding="utf-8") as file:

        file.write("=" * 70 + "\n")
        file.write("AI INCIDENT REPORT GENERATOR\n")
        file.write("=" * 70 + "\n\n")

        file.write(
            f"Generated On : {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}\n\n"
        )

        file.write(report)

        file.write("\n\n")
        file.write("=" * 70 + "\n")
        file.write("Generated by AI Incident Report Generator\n")
        file.write("=" * 70)

    return file_path